### ISSUE TITLE
Crie a classe [VendaDAO]

### ISSUE THREAD

**Issue by gpaganini** [gpaganini/lpmp-modulo2#10]

**Comment by luizalexandrew** [comment]
- [x] create(Venda venda) 
- [x] retrieve(id)
- [x] retrieveAll()
- [x] update(Venda venda)
- [x] delete(id)
- [x] delete(Venda venda)
- [ ] retreaveRelatorioVendas(Venda venda)
- [x] retreaveByClientes()
- [x] retreaveByData(Date dataInicial, Date dataFinal)

**Comment by luizalexandrew** [comment]
vendas


-incluir o retreaveRelatorioVendas(), aqui para cada venda apresentar o valor total e a data de cada venda; deverá ter uma coluna booleana que dirá se a venda foi totalmente recebida ou não (ou seja, se o valor total da venda é igual a soma dos recebimentos correlatos já baixados)

-incluir o retreaveByClientes()

-incluir o retreaveByData(Date dataInicial, Date dataFinal)

**Comment by luizalexandrew** [comment]
Se houver alguma assinatura de método errada basta informar e alterar
