### ISSUE TITLE
Crie a Classe [VendaItemDAO]

### ISSUE THREAD

**Issue by gpaganini** [gpaganini/lpmp-modulo2#11]

**Comment by luizalexandrew** [comment]
- [x] create(VendaItem vendaItem) 
- [x] retrieve(id)
- [x] retrieveAll()
- [x] update(VendaItem vendaItem)
- [x] delete(id)
- [x] delete(VendaItem vendaItem)
- [ ] retreaveByProduto()

**Comment by luizalexandrew** [comment]
vendas_itens

-incluir o retreaveByProduto(), aqui o relatório deverá incluir a soma e a média tanto da quantidade quanto do valor unitário por produto

**Comment by luizalexandrew** [comment]
Se houver alguma assinatura de método errada basta informar e alterar
