### ISSUE TITLE
Alterar atributo pk das classes de pk_classe para somente pk

### ISSUE THREAD

**Issue by gpaganini** [gpaganini/lpmp-modulo2#12]
Exemplo: 
public class Funcionario {   
    **private int pk_funcionario;**
    private String nome;
    private String cpf;

deverá ficar 

public class Funcionario {    
    **private int pk;**
    private String nome;
    private String cpf;

**Comment by luizalexandrew** [comment]
Lembrando que essa alteração é só nas classes Cliente, EnderecoCliente, Venda, VendaItem pois as outras já existem no projeto e não foi nosso grupo que fez

**Comment by luizalexandrew** [comment]
Pelo que vi está tudo ok, por isso fechando a Issue
