### ISSUE TITLE
Crie a classe [ClienteDAO]

### ISSUE THREAD

**Issue by gpaganini** [gpaganini/lpmp-modulo2#6]

**Comment by luizalexandrew** [comment]
- [ create(Cliente cliente) ] 
- [ retrieve(id) ] 
- [ retrieveAll() ] 
- [ update(Cliente cliente) ] 
- [ delete(id) ] 
- [ delete(Cliente cliente) ] 
- [ retreaveByEstado(String nomeEstado) ]
- [ retreaveByCidade(String nomeCidade) ]

**Comment by luizalexandrew** [comment]
- [x] create(Cliente cliente) 
- [x] retrieve(id)
- [x] retrieveAll()
- [x] update(Cliente cliente)
- [x] delete(id)
- [x] delete(Cliente cliente)
- [x] retrieveByEstado(String nomeEstado)
- [x] retrieveByCidade(String nomeCidade)

**Comment by luizalexandrew** [comment]
clientes

-incluir o retreaveByCidade(String nomeCidade)

-incluir o retreaveByEstado(String nomeEstado)

**Comment by luizalexandrew** [comment]
Se houver alguma assinatura de método errada basta informar e alterar
