### ISSUE TITLE
Crie a classe [EnderecoClienteDAO]

### ISSUE THREAD

**Issue by gpaganini** [gpaganini/lpmp-modulo2#9]

**Comment by luizalexandrew** [comment]
- [x] create(EnderecoCliente enderecoCliente) 
- [x] retrieve(id)
- [x] retrieveAll()
- [x] update(EnderecoCliente enderecoCliente)
- [x] delete(id)
- [x] delete(EnderecoCliente enderecoCliente)

**Comment by luizalexandrew** [comment]
Se houver alguma assinatura de método errada basta informar e alterar

**Comment by luizalexandrew** [comment]
Estava faltando o Delete passando o ID (int)

**Comment by luizalexandrew** [comment]
Implementei aqui, cuidado para não fechar a Issue com coisas faltando, pq senão esquecemos de fazer
